version: '2'
services:
    unipluswebadmin-app:
        image: unipluswebadmin
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://unipluswebadmin-postgresql:5432/UnipluswebAdmin
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    unipluswebadmin-postgresql:
        extends:
            file: postgresql.yml
            service: unipluswebadmin-postgresql
