version: '2'
services:
    unipluswebadmin-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/UnipluswebAdmin/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=UnipluswebAdmin
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
